---
- name: add nodesource key
  apt_key:
    data: "{{ lookup('file', 'nodesource.gpg.key') }}"
    state: present
  become: yes

- name: add nodesource packages to apt
  apt_repository:
    repo: "{{ item }} https://deb.nodesource.com/node_6.x trusty main"
    filename: nodesource
    state: present
  with_items:
    - deb
    - deb-src
  become: yes

- name: install nodejs
  apt: pkg=nodejs state=latest
  become: yes

- name: install yarn
  npm: name=yarn global=yes
  become: yes
