---
- name: "Fetch erlang solutions repo"
  get_url: "url=https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb dest=/tmp/erlang-solutions_1.0_all.deb"

- name: "Add erlang solutions repo to dpkg"
  apt: "deb=/tmp/erlang-solutions_1.0_all.deb update_cache=yes"
  become: "yes"

- name: "Install elixir"
  apt: "name={{ item }} state=present update_cache=yes"
  with_items:
    - "esl-erlang"
    - "elixir"
  become: "yes"
