---
- name: "Install postgresql and related libraries"
  apt: "pkg={{ item }} state=present"
  with_items:
    - "postgresql"
    - "postgresql-contrib"
    - "libpq-dev"
  become: "yes"

- name: "Trust all incoming connections in pg_hba.conf"
  replace: "dest=/etc/postgresql/9.3/main/pg_hba.conf regexp='(md5|peer)' replace='trust'"
  notify: "restart postgresql"
  become: "yes"
